import { db, categoriesTable, productsTable, couponsTable, bannersTable, usersTable } from "@workspace/db";

async function seed() {
  console.log("Seeding Aditya General Store data...");

  const categories = await db
    .insert(categoriesTable)
    .values([
      { name: "Fruits & Vegetables", icon: "carrot" },
      { name: "Dairy & Bakery", icon: "milk" },
      { name: "Atta, Rice & Dal", icon: "wheat" },
      { name: "Masala & Oil", icon: "flame" },
      { name: "Snacks & Beverages", icon: "cookie" },
      { name: "Personal Care", icon: "sparkles" },
      { name: "Household Needs", icon: "spray-can" },
    ])
    .returning();

  const byName = (n: string) => categories.find((c) => c.name === n)!.id;

  const products = [
    {
      categoryId: byName("Fruits & Vegetables"),
      name: "Fresh Tomatoes",
      description: "Farm-fresh red tomatoes, hand-picked daily.",
      price: "28.00",
      mrp: "35.00",
      unit: "1 kg",
      imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600",
      stock: 80,
      lowStockThreshold: 15,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Fruits & Vegetables"),
      name: "Onion",
      description: "Premium quality onions.",
      price: "32.00",
      mrp: "40.00",
      unit: "1 kg",
      imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600",
      stock: 100,
      lowStockThreshold: 20,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Fruits & Vegetables"),
      name: "Potato",
      description: "Fresh potatoes, great for everyday cooking.",
      price: "24.00",
      mrp: "30.00",
      unit: "1 kg",
      imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600",
      stock: 8,
      lowStockThreshold: 15,
      isBestSeller: false,
      isNewArrival: false,
    },
    {
      categoryId: byName("Dairy & Bakery"),
      name: "Amul Toned Milk",
      description: "Fresh toned milk, 500ml pouch.",
      price: "27.00",
      mrp: "27.00",
      unit: "500 ml",
      imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600",
      stock: 60,
      lowStockThreshold: 10,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Dairy & Bakery"),
      name: "Brown Bread",
      description: "Soft whole-wheat brown bread loaf.",
      price: "45.00",
      mrp: "50.00",
      unit: "400 g",
      imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600",
      stock: 40,
      lowStockThreshold: 10,
      isBestSeller: false,
      isNewArrival: true,
    },
    {
      categoryId: byName("Dairy & Bakery"),
      name: "Paneer",
      description: "Soft fresh paneer, rich in protein.",
      price: "90.00",
      mrp: "100.00",
      unit: "200 g",
      imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600",
      stock: 30,
      lowStockThreshold: 8,
      isBestSeller: false,
      isNewArrival: true,
    },
    {
      categoryId: byName("Atta, Rice & Dal"),
      name: "Aashirvaad Atta",
      description: "Whole wheat atta for soft rotis.",
      price: "255.00",
      mrp: "280.00",
      unit: "5 kg",
      imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600",
      stock: 50,
      lowStockThreshold: 10,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Atta, Rice & Dal"),
      name: "India Gate Basmati Rice",
      description: "Premium long-grain basmati rice.",
      price: "310.00",
      mrp: "350.00",
      unit: "5 kg",
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600",
      stock: 45,
      lowStockThreshold: 10,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Atta, Rice & Dal"),
      name: "Toor Dal",
      description: "Unpolished, high-quality toor dal.",
      price: "150.00",
      mrp: "165.00",
      unit: "1 kg",
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600",
      stock: 6,
      lowStockThreshold: 10,
      isBestSeller: false,
      isNewArrival: false,
    },
    {
      categoryId: byName("Masala & Oil"),
      name: "Fortune Sunflower Oil",
      description: "Refined sunflower cooking oil.",
      price: "180.00",
      mrp: "199.00",
      unit: "1 L",
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
      stock: 55,
      lowStockThreshold: 10,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Masala & Oil"),
      name: "MDH Garam Masala",
      description: "Authentic blend of Indian spices.",
      price: "85.00",
      mrp: "95.00",
      unit: "100 g",
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600",
      stock: 35,
      lowStockThreshold: 8,
      isBestSeller: false,
      isNewArrival: true,
    },
    {
      categoryId: byName("Snacks & Beverages"),
      name: "Lay's Classic Chips",
      description: "Crispy salted potato chips.",
      price: "20.00",
      mrp: "20.00",
      unit: "52 g",
      imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600",
      stock: 120,
      lowStockThreshold: 20,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Snacks & Beverages"),
      name: "Parle-G Biscuits",
      description: "India's favourite glucose biscuits.",
      price: "10.00",
      mrp: "10.00",
      unit: "100 g",
      imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600",
      stock: 200,
      lowStockThreshold: 30,
      isBestSeller: true,
      isNewArrival: false,
    },
    {
      categoryId: byName("Snacks & Beverages"),
      name: "Frooti Mango Drink",
      description: "Refreshing mango fruit drink.",
      price: "20.00",
      mrp: "20.00",
      unit: "200 ml",
      imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600",
      stock: 90,
      lowStockThreshold: 15,
      isBestSeller: false,
      isNewArrival: true,
    },
    {
      categoryId: byName("Personal Care"),
      name: "Colgate Toothpaste",
      description: "Cavity protection toothpaste.",
      price: "55.00",
      mrp: "60.00",
      unit: "100 g",
      imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600",
      stock: 70,
      lowStockThreshold: 15,
      isBestSeller: false,
      isNewArrival: false,
    },
    {
      categoryId: byName("Personal Care"),
      name: "Dove Soap",
      description: "Moisturizing beauty bar.",
      price: "48.00",
      mrp: "55.00",
      unit: "100 g",
      imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600",
      stock: 9,
      lowStockThreshold: 12,
      isBestSeller: false,
      isNewArrival: false,
    },
    {
      categoryId: byName("Household Needs"),
      name: "Vim Dishwash Gel",
      description: "Lemon-fresh dishwashing gel.",
      price: "95.00",
      mrp: "105.00",
      unit: "500 ml",
      imageUrl: "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=600",
      stock: 40,
      lowStockThreshold: 10,
      isBestSeller: false,
      isNewArrival: false,
    },
    {
      categoryId: byName("Household Needs"),
      name: "Surf Excel Detergent",
      description: "Powerful stain-removing detergent powder.",
      price: "140.00",
      mrp: "155.00",
      unit: "1 kg",
      imageUrl: "https://images.unsplash.com/photo-1610557892470-55d587ea3f57?w=600",
      stock: 25,
      lowStockThreshold: 10,
      isBestSeller: true,
      isNewArrival: false,
    },
  ];

  await db.insert(productsTable).values(products);

  await db.insert(couponsTable).values([
    {
      code: "ADITYA10",
      description: "10% off on your order",
      type: "percent",
      value: "10",
      active: true,
    },
    {
      code: "WELCOME50",
      description: "Flat ₹50 off",
      type: "flat",
      value: "50",
      active: true,
    },
  ]);

  await db.insert(bannersTable).values([
    {
      title: "Flash Sale: Up to 20% off groceries",
      imageUrl: "https://images.unsplash.com/photo-1543168256-418811576931?w=1200",
      linkText: "Shop Now",
      active: true,
    },
    {
      title: "Fresh Vegetables Delivered Daily",
      imageUrl: "https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=1200",
      linkText: "Explore",
      active: true,
    },
  ]);

  await db.insert(usersTable).values({
    name: "Guest User",
    phone: "9999999999",
    referralCode: "GUEST0001",
  });

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
